# Generated by Django 5.2.7 on 2025-10-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='answer_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
