# Generated by Django 5.2.7 on 2025-10-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0002_dummy_answer_text_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Quizlet.dummy')),
                ('anwer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='answer_text',
        ),
    ]
