# Generated by Django 5.2.7 on 2025-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0003_answer_remove_dummy_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='answer1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dummy',
            name='answer2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dummy',
            name='answer3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
