# Generated by Django 5.2.7 on 2025-11-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0004_dummy_answer1_dummy_answer2_dummy_answer3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='answer3',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(blank=True, max_length=100)),
                ('answer2', models.CharField(blank=True, max_length=100)),
                ('answer3', models.CharField(blank=True, max_length=100)),
                ('dummy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet.dummy', verbose_name='Вопросики')),
            ],
        ),
    ]
