# Generated by Django 5.2.7 on 2025-11-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0005_remove_dummy_answer1_remove_dummy_answer2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummy',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelTableComment(
            name='dummy',
            table_comment='Тут у нас вопросы храняться',
        ),
    ]
