# Generated by Django 5.2.7 on 2025-11-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0006_alter_dummy_options_alter_dummy_table_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
