# Generated by Django 5.2.7 on 2025-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0007_dummy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy',
            name='slug',
        ),
    ]
