# Generated by Django 5.2.7 on 2025-11-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0008_remove_dummy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer3',
        ),
    ]
