# Generated by Django 5.2.7 on 2025-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0010_quiz_question_delete_answer_delete_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PR', 'properly'), ('WR', 'wrong')], default='WR', max_length=2),
        ),
    ]
