# Generated by Django 5.2.7 on 2025-11-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0011_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_text',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тема квиза'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Quizlet.quiz')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='Quizlet_com_created_74b10a_idx')],
            },
        ),
    ]
