# Generated by Django 5.2.7 on 2025-11-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0012_alter_question_question_alter_quiz_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='quiz',
            new_name='quize',
        ),
    ]
