# Generated by Django 5.2.7 on 2025-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet', '0013_rename_quiz_comment_quize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_text',
            field=models.CharField(max_length=100, verbose_name='Тема квиза'),
        ),
    ]
